name: Project Ecom CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/database-name
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['4.4']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2q  xcv/
        with:
          node-version: ${{matrix.node-version}}

      - name: use MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
